version: '3.9'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel
    
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=instore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5441:5432
    networks:
      - laravel
  
  composer:
    image: composer:latest
    container_name: composer
    command: ['composer', 'install']
    depends_on:
      - php
    volumes:
      - ./src/:/app
    restart: always
    networks:
      - laravel
volumes:
  pg-data: